language: php

matrix:
  include:
  - php: 7.4
    dist: xenial
    sudo: required
    services:
      - mysql
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/scripts/create_users.sh
    script:
      - cd tests && ./test.sh
